name: Build and Test

on:
  push:
    branches: [ main ]
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test application

    permissions:
      checks:  write
      contents: read
      issues: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle and test application
        uses: gradle/actions/setup-gradle@v4

      - name: Run Gradle Build
        env:
          TZ: Europe/Berlin
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          LANGUAGE: en_US.UTF-8
          CI: true
        run: ./gradlew build --parallel --continue --console=plain

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/build/test-results/**/*.xml"
