name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
    outputs:
      released-version: "${{ steps.release.outputs.released-version }}"

    steps:
      - uses: actions/checkout@v4
        with:
          # Required for axion-release-plugin
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle and test application
        uses: gradle/actions/setup-gradle@v4

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github@roamingthings.de"
          git config user.name "GitHub Actions"
          ./gradlew release --console=plain

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish --console=plain

      - uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.release.outputs.released-version }}"
          artifacts: "build/libs/*.jar"
          generateReleaseNotes: true
